### ISSUE TITLE
2.0.0: Battenberg results folder empty ?!

### ISSUE THREAD

**Issue by leiendeckerlu** [cancerit/dockstore-cgpwgs#28]
Hi there,

after running the cgpwgs:2.0.0 pipeline on .a T/N-pair aligned with cgpmap the /battenberg/ subfolder in the results directory only has a /tmpBattenberg/ subfolder but does not include the actual result files that I would expect from the battenberg.pl pipeline script.

Is this intended and the battenberg.pl run is not part of the standard cgpwgs pipeline? And if so, why is a battenberg folder created?

Thank you!

**Comment by keiranmraine** [comment]
The default flow only generates the allele counts (the computationally heavy component) that can be used by battenberg.  Battenberg needs visual interpretation of results mid way through processing and when it was included for use in PanProstate and PanCancer projects was not sufficiently stable to run to completion without manual intervention.

We have maintained the same level of functionality, but do not plan to support full execution of Battenberg within this tool.
