### ISSUE TITLE
Help to run this dock file using singularity

### ISSUE THREAD

**Issue by xtmgah** [cancerit/dockstore-cgpwgs#30]
Hello, I am trying to run this dock pipeline using singularity, I pulled the image "dockstore-cgpwgs-1.1.3.simg" using singularity but I can't run any script? Is anyway wrong? For example, 

ds-cgpwgs.pl
bash: ds-cgpwgs.pl: command not found

Do I need to download the "ds-cgpwgs.pl:" from this GitHub? 

Also, I tried this:

singularity exec\
 --workdir /.../workspace  \
 --home /.../workspace:/home  \
 --bind /.../ref/human:/var/spool/ref:ro  \
 --bind /.../example_data/cgpwgs:/var/spool/data:ro  \
 dockstore-cgpwgs-${CGPWGS_VER}.simg  \
  ds-cgpwgs.pl

ERROR  : Image path dockstore-cgpwgs-.simg doesn't exist
ABORT  : Retval = 255

Can you show me how to run this? thanks.

**Comment by keiranmraine** [comment]
The error indicates it can't find the singularity image.  You indicate that when you generated the image it was saved as `dockstore-cgpwgs-1.1.3.simg` but in the error message it is looking for `dockstore-cgpwgs-.simg`.  This suggests that you no don't have the environment variable of `CGPWGS_VER` set in the terminal session used for execution.

You can change the command to specify the downloaded file, the examples use environment variables so we don't have to change them on every release.

**Comment by xtmgah** [comment]
Hello:

Thanks for your help. I try to fix this and run the following command, but still get different error:

singularity exec dockstore-cgpwgs-1.1.3.simg ds-cgpwgs.pl -h
/.singularity.d/actions/exec: 9: exec: ds-cgpwgs.pl: not found

Can you help? 

Can you simple explain what this path means for singularity? 

--workdir /.../workspace 
--home /.../workspace:/home 
--bind /.../ref/human:/var/spool/ref:ro 
--bind /.../example_data/cgpwgs:/var/spool/data:ro 

I am just new to singularity. Thanks for your help.

**Comment by keiranmraine** [comment]
Please see the singularity documentation for explanation of the params for the wrapper:

```
--workdir
--home
--bind
```

The `/.../` indicates some location on your local system that you want to expose to the image using the path to the right of the `:` as the internal path.

As a really simple test you could try:

```
singularity exec dockstore-cgpwgs-1.1.3.simg echo \$PATH
```

Followed by:

```
singularity exec dockstore-cgpwgs-1.1.3.simg which ds-cgpwgs.pl
```

If these both fail to work could you get the version of singularity you are using.

**Comment by keiranmraine** [comment]
Please note I edited the last comment `echo \$PATH`

**Comment by xtmgah** [comment]
Thanks for your quick response. Just did it, But nothing happen:

zhangt8@cn3197:/data/zhangt8/software/ascatNgs$ singularity exec dockstore-cgpwgs-1.1.3.simg echo \$PATH
$PATH
zhangt8@cn3197:/data/zhangt8/software/ascatNgs$ singularity exec dockstore-cgpwgs-1.1.3.simg which ds-cgpwgs.pl
zhangt8@cn3197:/data/zhangt8/software/ascatNgs$ 

Here is my signaurlarity version 

zhangt8@cn3197:/data/zhangt8/software/ascatNgs$ singularity --version 
2.5.2-dist

Any suggestion?

**Comment by keiranmraine** [comment]
I've identified the problem.  You are using 1.1.3.  The first version we officially setup for use with singularity was 2.0.0 (we needed to expose more options).

The documentation is for 2.0.0, so if you really need to use 1.1.3 you would be needing to reference the script `ds-wrapper.pl` instead of `ds-cgpwgs.pl`.
