### ISSUE TITLE
Reference bundle for 38

### ISSUE THREAD

**Issue by W4RJ4** [cancerit/dockstore-cgpwgs#31]
Hi, Keiran, thanks for your answer on this same issue a several days ago. You said i should raise it here.

>  Hi, I have a question regarding this workflows ability to work with 38 reference files? And if it's possible to run it with them, where i can find reference bundles for 38, or if you can point me to the method or tool that was used to generate these existing 37 reference bundles. Thanks.

**Comment by keiranmraine** [comment]
@W4RJ4 we are currently in the process of generating a bundle for this which includes the normal panel (which is challenging to create).

We expect it won't be too much longer, 2-4 weeks (summer holidays etc).

**Comment by phansol** [comment]
Hi, Kerian. 
Are you still working on it? If it is done, please let me download.

**Comment by keiranmraine** [comment]
If you haven't seen it already take a read of this wiki page:

https://github.com/cancerit/dockstore-cgpwgs/wiki/Reference-archives#human-grch38
