### ISSUE TITLE
Ascat error

### ISSUE THREAD

**Issue by DominikGlodzik** [cancerit/dockstore-cgpwgs#36]
Dear Colleagues

Please could you advise if you have encountered the following error that I paste below? If so, please advise.

Kind regards
Dominik

I am running the image through singularity as follows (WGS 40x/80x):
`        ds-cgpwgs.pl \
         -reference /var/spool/ref/core_ref_GRCh37d5.tar.gz \
        -annot /var/spool/ref/VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz \
        -snv_indel /var/spool/ref/SNV_INDEL_ref_GRCh37d5.tar.gz \
         -cnv_sv /var/spool/ref/CNV_SV_ref_GRCh37d5_brass6+.tar.gz \
         -subcl /var/spool/ref/SUBCL_ref_GRCh37d5.tar.gz \
         -exclude NC_007605,hs37d5,GL% \
         -species Human \
         -assembly GRCH37D5 \
         -tumour  /var/spool/data/tum/tum.bam \
         -normal /var/spool/data/norm/norm.bam \
         -tidx  /var/spool/data/tum/tum.bam.bai \
         -nidx  /var/spool/data/norm/norm.bam.bai \
         -cavereads 800000 \
         -cores 12 \
         -qcset /var/spool/ref/qcGenotype_GRCh37d5.tar.gz`

Error in ASCAT log:
`+ cut -f 1-3 /home/WGS_MNM00026_vs_MNM00025/ascat/tmpAscat/SnpGcCorrections.tsv
+ cd /home/WGS_MNM00026_vs_MNM00025/ascat/tmpAscat/ascat
+ /usr/bin/Rscript /opt/wtsi-cgp/lib/perl5/auto/share/module/Sanger-CGP-Ascat-Implement/ascat/runASCAT.R /opt/wtsi-cgp/lib/perl5/auto/share/modu
le/Sanger-CGP-Ascat-Implement/ascat /home/WGS_MNM00026_vs_MNM00025/ascat/tmpAscat/SnpPositions.tsv /home/WGS_MNM00026_vs_MNM00025/ascat/tmpAscat
/SnpGcCorrections.tsv MNM00026 MNM00026.count MNM00025 MNM00025.count XX 24 /home/WGS_MNM00026_vs_MNM00025/ascat/tmpAscat/ascat/MNM00026.Rdata
Error in apply(corr_tot, 1, function(x) sum(abs(x * length_tot))/sum(length_tot)) :
  dim(X) must have a positive length
Calls: ascat.GCcorrect -> apply
Execution halted
Command exited with non-zero status 1
445.93user 1.63system 7:28.04elapsed 99%CPU (0avgtext+0avgdata 2161004maxresident)k
15432inputs+440512outputs (33major+658054minor)pagefaults 0swaps`

**Comment by DominikGlodzik** [comment]
I believe the error arises because the allele counts files are all zeros, e.g.. /ascat/tmpAscat/allele_count/MNM00025.21.allct looks like

`#CHR	POS	Count_A	Count_C	Count_G	Count_T	Good_depth

21	9411410	0	0	0	0	0
21	9412503	0	0	0	0	0
21	9413584	0	0	0	0	0
21	9416257	0	0	0	0	0
21	9417284	0	0	0	0	0
21	9418371	0	0	0	0	0
21	9419909	0	0	0	0	0
21	9421531	0	0	0	0	0
21	9425605	0	0	0	0	0`
...

**Comment by DominikGlodzik** [comment]
I can also recreate the problem with 0 allele counts from inside of the container.

Running alleleCounter with a subset of Ascat loci and same bam file, all allele counts returned are zero.

The bamfile looks otherwise healthy on inspection through samtools view.

This makes me think it is a problem with alleleCounter within the image. Any suggestions appreciated.

Could the singularity image somehow be related to this problem? I can try Docker instead.

Any advice appreciated

**Comment by keiranmraine** [comment]
Hi,

This normally happens when the input BAM/CRAM file has a chromosome names with a 'chr' prefix.  Can you check the headers?

```
samtools view -H input.bam | grep '^@SQ'
```

The reference bundles assume no `chr` prefix and that the inputs were created using cgpmap with the provided reference bundles (which we know is not ideal for all)

**Comment by keiranmraine** [comment]
Another common cause can be a corrupt BAM index.  Seen with `*.bai` files.

**Comment by keiranmraine** [comment]
This matched the confirmed suspicions in the linked item on battenberg.
