### ISSUE TITLE
AlleleCount error when attempting to run Battenberg

### ISSUE THREAD

**Issue by ValerieCrolley** [cancerit/dockstore-cgpwgs#37]
To Whom it May Concern,

I have been trying to use Battenberg on my local HPC cluster using the dockstore-cgpwgs image in singularity using the following command:

singularity exec /home/.../dockstore-cgpwgs-2.0.0.simg battenberg.pl \
-o /.../exp/PD12808 \
-r /home/regmvcr/Scratch/reference/hg19.fa.fai \
-tb /home/.../*SAMPLENAME_tumour*.bam \
-nb /home/.../*SAMPLENAME_normal*.bam \
-ge XY \
-e /home/...reference/impute/impute_info.txt \
-u /home/.../reference/1000genomesloci \
-ig /home/.../reference/ignore_contigs.txt \
-gc /home/.../battenberg_wgs_gc_correction_1000g_v3.tar.gz \
-g /home/... \
-c /home/.../reference/probloci_270415.txt \
-pr WGS \
-t 8

It runs without producing an error message endlessly unless it is killed. However, the output consists of allele frequency files which consist entirely of 0s, like this:

#CHR    POS     Count_A Count_C Count_G Count_T Good_depth
13	19020013        0	0	0	0	0
13	19020047        0	0	0	0	0
13	19020095        0	0	0	0	0
13	19020145        0	0	0	0	0
13	19020341        0	0	0	0	0

and Sanger_CGP_Battenberg_Implement_battenberg_allelecount.x files in the progress folder which are entirely blank.

I've followed the suggestions as per this alleleCount question:
https://github.com/cancerit/alleleCount/issues/41
But none of the suggestions there fixed the problem. 

It looks to me like someone else is having a similar problem when trying to run ASCAT:
https://github.com/cancerit/dockstore-cgpwgs/issues/36

Since I'm relatively new to all of this, I'm not entirely sure if I'm doing something wrong or if there is an issue with the alleleCount function in the singularity image. 

Any help on solving/circumventing the problem would be greatly appreciated.

**Comment by keiranmraine** [comment]
Hi,

This normally happens when the input BAM/CRAM file has a chromosome names with a 'chr' prefix.  Can you check the headers?

```
samtools view -H input.bam | grep '^@SQ'
```

The reference bundles assume no `chr` prefix and that the inputs were created using cgpmap with the provided reference bundles (which we know is not ideal for all)

**Comment by ValerieCrolley** [comment]
Thank you for getting back to me so quickly! You're right, my input bam files have chr prefixes by the look of things. Theoretically updating the reference files to include the chr prefix (not that I know how to do this) would solve the issue, right?

**Comment by ValerieCrolley** [comment]
Just so you know, I updated the 1000 genomes loci files to all have a 'chr' prefix in front of the chromosome number. On re-running the script, the allele frequency files are no longer empty but the Sanger_CGP_Battenberg_Implement_battenberg_allelecount.x files in the progress folder are still blank and the script as a whole still runs endlessly until it is killed. Would it be better to attempt to alter the BAM headers to remove the 'chr' prefix or do I have to modify any of the other reference files?

**Comment by keiranmraine** [comment]
If you need to use battenberg see the cgpBattenberg wiki for details of how to update all relevant reference files:

https://github.com/cancerit/cgpBattenberg/wiki/Reference-name-conventions

Please note that you will need to update the complete set of reference files.  Alternatively you can re-head the BAM files, but that is less than ideal if you have many.

**Comment by ValerieCrolley** [comment]
Dear Keiran,

Thank you for getting back to me. I updated the relevant reference files as per your link, and I'm still getting the same issue (i.e. the allele count step runs endlessly producing blank output files until it is killed). 

I'm going to try 2 further fixes:
1) re-generating the BAM index files in case they were corrupted (as per the issue I linked in alleleCount - I have already tried sorting the reference files and it has made no difference)
2) removing the 'chr' prefixes from the BAM files

I'll let you know if either solution fixes the issue.

**Comment by ValerieCrolley** [comment]
Update:

1) I tried running battenberg with updated BAM index files and have the same issue - the initial allele count step runs and runs until killed, producing blank Sanger_CGP_Battenberg_Implement_battenberg_allelecount.x files in the tmpBattenberg/progress folder.

2) Running battenberg on BAM files with the 'chr' prefix removed (matched with the original reference files and a copy of hg19.fa/fa.fai also missing the 'chr' prefix gave me the following error message:
`"/usr/bin/time /*PATH*/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_gc_correct.0.sh 1> /*PATH*/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_gc_correct.0.out 2> /*PATH*/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_gc_correct.0.err" unexpectedly returned exit value 1 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 270.
 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 268
`
Using the original hg19.fa file causes the same error message as above.

I'm really not sure what else to do to fix this. Any help is much appreciated.

**Comment by keiranmraine** [comment]
The `progress` folder does not contain data files.  These are just empty files recording that a step has completed successfully.

The error above shows you where to get the output of the step errors:

`/*PATH*/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_gc_correct.0.err`

(we have an update for the wrapper code which makes this more obvious)

**Comment by ValerieCrolley** [comment]
Thanks for clarifying - the blank files now make much more sense.

I actually found the appropriate log files just before you replied, and solved the error message noted above (turns out I hadn't unpacked the gc correction file...)

I'm now having an issue with impute - it appears to be looking for chromosome 24 in human data. The error log I get is below:

`+ cd /*PATH*/tmpBattenberg
+ /usr/bin/Rscript -e 'library(Battenberg);  generate.impute.input.wgs(chrom=24, tumour.allele.counts.file="*TUMOUR_SAMPLE*_alleleFrequencies_chr24.txt", normal.allele.counts.file="*NORMAL_SAMPLE*_alleleFrequencies_chr24.txt", output.file="*TUMOUR_SAMPLE*_impute_input_chr24.txt", imputeinfofile="/*PATH*/reference/impute/impute_info.txt", is.male="TRUE", problemLociFile="/*PATH*/reference/probloci_270415_noChr.txt", useLociFile=NA, heterozygousFilter=0.1) '

Error in file(file, "rt") : cannot open the connection
Calls: generate.impute.input.wgs -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted
Command exited with non-zero status 1
0.44user 0.04system 0:03.38elapsed 14%CPU (0avgtext+0avgdata 51148maxresident)k
74inputs+16outputs (1major+17453minor)pagefaults 0swaps`

Setting the reference genome to 'Human' hasn't fixed the issue.

Thank you for your help - as I said, I'm new at this and no one else in my team has ever used these tools.

**Comment by keiranmraine** [comment]
Battenberg is no longer embedded in cgpwgs.
