### ISSUE TITLE
Suggested exclusion parameters for GrCh38

### ISSUE THREAD

**Issue by ardydavari** [cancerit/dockstore-cgpwgs#47]
Line 23 of cgpwgs.cwl contains suggested exclude parameters for GRCh37, but does not include the suggested default parameters for GrCh38. 

```
WARNING: The usual setting for 'exclude' is 'NC_007605,hs37d5,GL%' (human GRCh37/NCBI37). Examples
```

This was my best guess, but I am not sure if this is correct:
```
"chr1_%,chr2_%,chr3_%,chr4_%,chr5_%,chr6_%,chr7_%,chr8_%,chr9_%,chr10_%,chr11_%,chr12_%,chr13_%,chr14_%,chr15_%,chr16_%,chr17_%,chr18_%,chr19_%,chr20_%,chr21_%,chr22_%,chrX_%,chrY_%,chrUn%,HLA%,chrEBV"
```

**Comment by keiranmraine** [comment]
That will work, however this is a much shorter alternative:

`chrUn%,HLA%,%_alt,%_random,chrM,chrEBV`
