### ISSUE TITLE
samtools: error while loading shared libraries: libhts.so.2

### ISSUE THREAD

**Issue by R-Cardenas** [cancerit/dockstore-cgpwgs#49]
Hi
I have built a singularity image 
singularity build --remote cgpwgs_v2.0.0.simg docker://quay.io/wtsicgp/dockstore-cgpwgs:2.0.0

But upon inputting all of the required fields:

singularity exec images/cgpwgs_v2.0.0.simg ds-cgpwgs.pl \
-r /cgpwgs_ref/core_ref_GRCh37d5.tar.gz \
-a /cgpwgs_ref/VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz \
-si /cgpwgs_ref/SNV_INDEL_ref_GRCh37d5.tar.gz \
-cs /cgpwgs_ref/CNV_SV_ref_GRCh37d5_brass6+.tar.gz \
-sc /cgpwgs_ref/SUBCL_ref_GRCh37d5.tar.gz \
- qc /cgpwgs_ref/qcGenotype_GRCh37d5.tar.gz \
-t /test_data/HCC1143_ds/HCC1143.bam \
-tidx /test_data/HCC1143_ds/HCC1143.bam.bai \
-n  /test_data/HCC1143_ds/data/HCC1143_BL.bam \
-nidx /test_data/HCC1143_ds/HCC1143_BL.bam.bai \
-e 'MT,GL%,hs37d5,NC_007605' 

 I get the following error and I cant figure it out!

samtools: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory
Can't close(GLOB(0x28248e0)) filehandle: '' at /opt/wtsi-cgp/bin/ds-cgpwgs.pl line 232

Any help would be appreciated!
Many thanks
Ryan

**Comment by keiranmraine** [comment]
There is a singularity bug:

https://github.com/sylabs/singularity/issues/3594

You have to invoke as `singularity exec --cleanenv ...`

**Comment by R-Cardenas** [comment]
Thanks a million - worked a charm
