### ISSUE TITLE
alleleCounter behavior on overlapping read pairs

### ISSUE THREAD

**Issue by DominikGlodzik** [cancerit/dockstore-cgpwgs#52]
Hello CancerIT team,

could you explain what the behavior of alleleCounter is when it encounters read pairs where the reads overlap? Are such pairs counted for depth?

This becomes relevant when DNA is very fragmented.

All the best
Dominik

**Comment by keiranmraine** [comment]
AlleleCount was updated in v4 to handle overlapping fragments as a single count.  This version of the container has v4.0.2:

Please see the release notes: https://github.com/cancerit/alleleCount/releases/tag/v4.0.0
