### ISSUE TITLE
No co-located bas file found for tumour

### ISSUE THREAD

**Issue by cahaisv** [cancerit/dockstore-cgpwgs#59]
I'm trying to use dockstore-cgpwgs_2.1.1.sif with singularity.
It seems to require bas file along with the bam file :
No co-located bas file found for tumour, expected at /var/spool/data/tumor.bam.bas at /opt/wtsi-cgp/bin/ds-cgpwgs.pl line 81.
But I haven't found any documentation on how to create this type of index file.

**Comment by keiranmraine** [comment]
The tools are included in the docker image `bam_stats`:

```
$ bam_stats -h
Usage: bam_stats -i file -o file [-p plots] [-r reference.fa.fai] [-h] [-v]

-i --input          File path to read in.
-o --output         File path to output.

Optional:
-r --ref-file       File path to reference index (.fai) file.
                    NB. If cram format is supplied via -b and the reference listed in the cram header can't be found bam_stats may fail to work correctly.
-a --rna            Uses the RNA method of calculating insert size (ignores anything outside ± ('sd'*standard_dev) of the mean in calculating a new mean)
-@ --num_threads    Use thread pool with specified number of threads.

Other:
-h --help           Display this usage information.
-v --version        Prints the version number.
```

See the wiki for how to execute the image under docker or singularity replacing `ds-cgpwgs.pl` onwards in the command.
