### ISSUE TITLE
Non-unique row names for ascat SNP positions

### ISSUE THREAD

**Issue by gmaci** [cancerit/dockstore-cgpwgs#6]
I get the following error during Sanger_CGP_Ascat_Implement_ascat.0

Error in `row.names<-.data.frame`(`*tmp*`, value = value) :
  duplicate 'row.names' are not allowed
Calls: rownames<- -> row.names<- -> row.names<-.data.frame
In addition: Warning message:
non-unique values when setting 'row.names': '10000159076', '10001443180', '10001464892', '10001580662', '10002969047', '10003714170', '10004604986', '10005716858', '10006222744', '10007144174', '10007615195', '10008597988', '10008638235', '10008711757', '10008719519', '10008851426', '10009166345', '10010104492', '10010340044', '10010514599', '10010801161', '10013103202', '10013411415', '10013685551', '10013875720', '10016305792', '10016395866', '10017260290', '10017591228', '10018459282', '10018906507', '10018984666', '10019342086', '10020000428', '10021349368', '10023396508', '10023818927', '10023832872', '10024423030', '10024838291', '10026182328', '10026345258', '10026483183', '10027469678', '10028123364', '10028123716', '10028250952', '10032085493', '10033257247', '10033411435', '10033690581', '10034577697', '10035410291', '10036635494', '1004389199', '10044013493', '10044496971', '1004482610', '10044962660', '10049591718', '10049911701', '10049918427', '1005002367', '10050263201', [... truncated]
Execution halted
Command exited with non-zero status 1
43.08user 4.19system 0:47.89elapsed 98%CPU (0avgtext+0avgdata 942276maxresident)k
25768inputs+85432outputs (62major+791407minor)pagefaults 0swaps

**Comment by keiranmraine** [comment]
Can you confirm that you have re-tried this?   I've pulled the data files from the ftp site and confirmed that there are no duplicates:

```
ubuntu@dockstore-trusty:~/data$ wc -l CNV_SV_ref/ascat/SnpGcCorrections.tsv ref/CNV_SV_ref/ascat/SnpGcCorrections.tsv 
  1855236 CNV_SV_ref/ascat/SnpGcCorrections.tsv
  1855236 ref/CNV_SV_ref/ascat/SnpGcCorrections.tsv
  3710472 total
ubuntu@dockstore-trusty:~/data$ cut -f 2,3 CNV_SV_ref/ascat/SnpGcCorrections.tsv | sort | uniq | wc -l
1855236
```

I'm not discounting an issue in the merging of the separate per chromosome allele counts within ascatNgs, just confused as this works in my hands (and in our pipeline).

**Comment by gmaci** [comment]
Sorry it looks like I was still pointing to the old file. Working now. Thanks!
