### ISSUE TITLE
cannot run cgpwgs

### ISSUE THREAD

**Issue by leovam** [cancerit/dockstore-cgpwgs#62]
Hi, I am trying to run cgpwgs within docker and the first thing I wanted to do is to test on the example data by following the wiki:
1. I downloaded the Reference data into my local PC in ```/home/leo/Desktop/SequenceSimulator/sanger_pipeline/ref```
2. since the Reference data download code unpack the data, then all the option just need to point to  ```ref```
3. I downloaded the example file: COLO-829.bam for tumor, COLO-829-BL.bam for normal and the corresponding index files, then rename them to tumor.bam, tumor.bam.bai, normal.bam, normal.bam.bai, respectively, save them to ```/home/leo/Desktop/SequenceSimulator/sanger_pipeline/data```
4. then I just run the the pipeline by following the ```Run command``` on Wiki:
```
sudo docker run -d \
--read-only --tmpfs /tmp \
--env HOME=/var/spool/results \
-v /home/leo/Desktop/SequenceSimulator/sanger_pipeline/ref:/var/spool/ref:ro \
-v /home/leo/Desktop/SequenceSimulator/sanger_pipeline/data:/var/spool/data:ro \
-v /home/leo/Desktop/SequenceSimulator/sanger_pipeline/results:/var/spool/results:rw \
quay.io/wtsicgp/dockstore-cgpwgs:2.1.1 \
ds-cgpwgs.pl \
-r /var/spool/ref \
-a /var/spool/ref \
-si /var/spool/ref \
-cs /var/spool/ref \
-qc /var/spool/ref \
-pl 3.65 -pu 1.0 \
-e 'MT,GL%,hs37d5,NC_007605' \
-t /var/spool/data/tumor.bam \
-tidx /var/spool/data/tumor.bam.bai \
-n /var/spool/data/normal.bam \
-nidx /var/spool/data/normal.bam.bai \
-o /var/spool/results
```
But when I hit ```Enter```, I got a series of numbers and letters: ```ba0c2460434a722a9df47dd20f1b2b62d7f93d959dded18f24ae4c47eb69b164``` and nothing happened

![image](https://user-images.githubusercontent.com/22210858/125137824-7298ac80-e0db-11eb-9710-3e319c37ee45.png)
 I also could not find any output in the ```results``` folder on my own PC, can someone help me with this? Thanks!

**Comment by keiranmraine** [comment]
You have executed docker in a detached mode resulting in the ID of the container started by the command being output:

```
docker run --help
...
-d, --detach                         Run container in background and print container ID
```

This command will show containers running or stopped on your system, the first few characters of the value above can be used for filter

```
docker ps -a | grep ba0c246
```

If you want the job to start in the foreground:

```
# replace
sudo docker run -d \
...
# with 
sudo docker run -ti --rm \
...
```

Additionally, I recommend you have your docker properly configured so that you do not need to run `sudo`.

**Comment by leovam** [comment]
thanks for your response. Now I can make the tool run without root privileges. However, I wonder what the final output should be for the example code on the example sample? The tool has run for several hours on my own PC (using 4 cores) and then dead. I suppose there should be vcf for each type of mutations (snv, cnv, sv) but I could only be able similar files under the **ascat** and **pindel** folder, for **brass** and **caveman** folder, there is only one folder called **tmpBrass** and **tmpCaveman**:
![image](https://user-images.githubusercontent.com/22210858/125345344-6eac9a80-e326-11eb-898f-c0753b1e482a.png)
inside which, there are no vcf or vcf.gz files found. Can you tell what might be wrong? Thanks!

**Comment by leovam** [comment]
according to the flow-chart, the program needs to go through 6 blocks, however, it has been stuck at block 4 for a couple of hours:
![image](https://user-images.githubusercontent.com/22210858/125362785-79bef500-e33d-11eb-815e-30cc5a5458a3.png)

Is this normal?

**Comment by keiranmraine** [comment]
This analysis is expected to be run on compute with ~18 cpus to turnaround data in under 24 hours for WGS depth of 30-50x.  Be aware that required memory is ~4-6GB/cpu, so it is possible the program has entered perpetual swap if you have don't have a huge amount of memory.

You can see the container statistics via `docker info $CONTAINER_ID` if you think it is stuck.

**Comment by keiranmraine** [comment]
Sorry, I mean `docker stats $CONTAINER_ID`.
