### ISSUE TITLE
Can this be run on WXS data?

### ISSUE THREAD

**Issue by d-henness** [cancerit/dockstore-cgpwgs#67]
I noticed in the refs directory for pindel and caveman there are files for WGS and WXS. If I replace the content of the WGS files with the content of the WXS files, is there anything else I would need to do to run on WXS data correctly?

**Comment by keiranmraine** [comment]
You want the sister repo:

https://github.com/cancerit/dockstore-cgpwxs

**Comment by d-henness** [comment]
Thanks!
