### ISSUE TITLE
Generating alternative reference sets 

### ISSUE THREAD

**Issue by Lillianwu0314** [cancerit/dockstore-cgpwgs#68]
Hi all,

I'd like to perform some WGS analysis using the newly released CHM13-T2T human genome. I was just wondering if there was a guide on how I could prepare reference sets for this genome?

Thanks,
Lillian

**Comment by AndyMenzies** [comment]
Hi Lillian

I have edited the cgpwgs [github wiki page on the reference bundles](https://github.com/cancerit/dockstore-cgpwgs/wiki/Reference-archives) to include links to the reference generation for each underlying algorithm.  Hopefully that will give you some pointers in the right direction.

I will repeat a disclaimer I added to the page here. We make use of a lot of external data resources, like Ensembl and UCSC.  If the build you want to use isn't supported by those resources you are going to struggle in generating a complete set of reference files.

Andy
